name: Distribute Grain
on:
  # A new Cred interval every Sunday. We'll distribute Grain 5 minutes
  # after the new interval
  schedule:
    - cron: 5 0 * * 0 # 00:05 UTC, 16:05 PST
  push:
    branches:
      - "graintest-*" # won't actually update ledger or deploy frontend

jobs:
  distribute-grain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "[debug] Check GitHub event name"
        # This is used to determine whether we actually deploy to GitHub
        # Pages, so we print it upfront to aid with debugging.
        run: echo ${{ github.event_name }}

      - name: Install Packages ğŸ”§
        run: yarn --frozen-lockfile


      - name: Commit Ledger ğŸ’¾
        run: |
          git config user.name 'credbot'
          git config user.email 'credbot@users.noreply.github.com'
          git add data/ledger.json
          git commit --allow-empty -m 'Auto-update ledger'
      
      - name: Push Ledger
        run: git push
      
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # Required to make github pages deployment work correctly

      - name: Generate Frontend ğŸ—
        run: |
          yarn site
          rm -rf ./site/{output,data,config,sourcecred.json}
          cp -r ./{output,data,config,sourcecred.json} ./site/

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.5.7
        if: "${{ github.event_name == 'schedule' }}"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
